name: Build Sky1 GNOME Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Register qemu/binfmt for multiarch
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo live-build parted dosfstools qemu-utils xz-utils debootstrap qemu-user-static binfmt-support

      - name: Build GNOME Image
        run: |
          sudo ./scripts/build.sh gnome desktop image main

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sky1-linux-gnome-desktop
          path: |
            *.img.xz
            *.img
          if-no-files-found: error
          retention-days: 7
